### ISSUE TITLE
runLeNet5.sh and runMobileNetV2.sh does not work

### ISSUE THREAD

**Issue by LIUQyou** [TeCSAR-UNCC/gem5-SALAM#19]
Hi,

 I am trying to run runLeNet5.sh and MobileNetV2.sh. It seems I encountered the problem belowing:
For MobileNetV2.sh:
```
head_top Profile Loaded
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "build/ARM/python/m5/main.py", line 455, in main
    exec(filecode, scope)
  File "configs/SALAM/generated/fs_mobilenetv2.py", line 345, in <module>
    test_sys = build_test_system(np)
  File "configs/SALAM/generated/fs_mobilenetv2.py", line 229, in build_test_system
    mobilenetv2.makeHWAcc(args, test_sys)
  File "/home/quliu/Desktop/gem5-SALAM/configs/SALAM/generated/mobilenetv2.py", line 1432, in makeHWAcc
    buildhead(args, system, system.head)
  File "/home/quliu/Desktop/gem5-SALAM/configs/SALAM/generated/mobilenetv2.py", line 51, in buildhead
    AccConfig(clstr.head_top, ir, config)
  File "/home/quliu/Desktop/gem5-SALAM/configs/SALAM/HWAccConfig.py", line 45, in AccConfig
    inst_list = yaml_inst_list['hw_config'][current_acc]['instructions'].keys()
KeyError: 'head_top'
```
For runLeNet5.sh:
The script has problems and it doesnot work.  
Could you give me some hints on how to fix it?
Thanks
Best,
Liu

**Comment by zephan-spencer** [comment]
# MobileNetV2 
Just downloaded a fresh build to try to recreate your mobilenet issue and I couldn't. 

Can you send the head_top definition out of <configs/SALAM/generated/mobilenetv2.py> ? 

It looks like this on my machine: 
```c
# head_top Definition
acc = "head_top"
ir = "/home/<username>/gem5-SALAM/benchmarks/mobilenetv2/hw/ir/head/top.ll"
config = "/home/<username>/gem5-SALAM/benchmarks/mobilenetv2//config.yml"
clstr.head_top = CommInterface(devicename=acc, gic=gic, pio_addr=0x100200c0, pio_size=128)
AccConfig(clstr.head_top, ir, config)
```
You should get the exact same definition. From your error is looks like clstr.head_top is never being assigned, which is odd. 

I'm running it by just using:

```bash
./mobilenetv2.sh
```

# LeNet5

Welp, that was just entirely broken as you said. I restructured most of the files and edited the script so that it all works together. There are three different unroll presets that we have for LeNet5 & three different system configurations. The most basic system would be no_unroll with a naive system. Feel free to open another issue if you want to discuss the LeNet5 stuff in depth. 

Once you build the benchmark you want, you should be able to run it by running a command like this: 

```bash
./runLeNet5.sh -u no_unroll -b naive
```

I've validated that the systems without unrolling work, but you might run into some issues for kernel/channel unroll. Feel free to let me know if you do.
