### ISSUE TITLE
X86-arch

### ISSUE THREAD

**Issue by Didi-1221** [TeCSAR-UNCC/gem5-SALAM#22]
Hi there,
does gem5-SALAM  supports X86?
Thank you

**Comment by zephan-spencer** [comment]
Hi Didi,

Sorry for the late response. It's been awhile since I've thought about this, so I'm going to do my best to remember that answer :). 

We shouldn't have a problem looking at X86 IR, but what isn't supported right now is X86 interrupts. So, when you go to build it for x86 it will complain because we only have ARM enabled in scons. 

Our proposed solution has been to develop a "global" GIC that handles whatever ISA is needed, but we don't have that *yet*. If you're interested in that actually working, feel free to reply here and let us know.

**Comment by zephan-spencer** [comment]
Closing for now, if interested in this feel free to comment here and we can reopen this.
