### ISSUE TITLE
File I/O

### ISSUE THREAD

**Issue by ashriram** [TeCSAR-UNCC/gem5-SALAM#8]
Is there any way to do file I/O within the host code ? For example, get the benchmarks to read input files?

**Comment by samerogers** [comment]
File I/O is supported in the Syscall Emulation and Full System simulation modes of gem5. The benchmarks provided with gem5-SALAM are built on gem5's full system simulation model, however they are working in a baremetal system (i.e. no OS for system calls). You can use the same configuration files used in the benchmarks to integrate accelerators into Syscall Emulation or Full System OS simulations, since the accelerators and other devices act like any other memory-mapped I/O devices in gem5.
